name = "Alphabit Theme"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = ["blog","responsive","personal","google analytics","portfolio"]
features = ["blog","responsive","personal"]
min_version = "0.1"

[author]
  name = "Erwin"
  homepage = ""

[original]
  name = "Alphabit Theme"
  author = "Erwin"
  homepage = ""
  repo = ""
